n = input('digite : ')
print(' seu tipo primitivo: ', type(n))
print('so tem espacos?', n.isspace())
print("e um numero?", n.isnumeric())
print('e alfabetico?', n.isalpha())
print('e alfanumerico?', n.isalnum())
print('esta em maiusculo?', n.isupper())
print('esta em minusculo?', n.islower())
print('esta capitalizada?', n.istitle())
